apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  pg_hba.conf: |
    local   all             postgres                                peer
    host    all             all             0.0.0.0/0               md5

  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
